CREATE TABLE gamesnet_games (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  cover TEXT DEFAULT 'https://www.ajactraining.org/wp-content/uploads/2019/09/image-placeholder.jpg',
  description TEXT NOT NULL,
  rated TEXT NOT NULL,
  platforms TEXT NOT NULL,
  date_added TIMESTAMP DEFAULT now() NOT NULL
);
