CREATE TABLE gamesnet_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT,
  date_joined TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE gamesnet_games
  ADD COLUMN
    user_id INTEGER REFERENCES gamesnet_users(id)
    ON DELETE SET NULL;
    