CREATE TABLE gamesnet_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    rating INTEGER NOT NULL,
    review TEXT NOT NULL,
    date_posted TIMESTAMP DEFAULT now() NOT NULL,
    game_id INTEGER
        REFERENCES gamesnet_games(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES gamesnet_users(id) ON DELETE CASCADE NOT NULL
);
